export const FETCH_TODO_REQUEST = 'FETCH_TODO_REQUEST';
export const FETCH_TODO_REQUEST_SUCCESS = 'FETCH_TODO_REQUEST_SUCCESS';
export const FETCH_TODO_REQUEST_FAILED = 'FETCH_TODO_REQUEST_FAILED';

export const FETCH_TODO_ADD_REQUEST = 'FETCH_TODO_ADD_REQUEST';
export const FETCH_TODO_ADD_REQUEST_SUCCESS = 'FETCH_TODO_ADD_REQUEST_SUCCESS';
export const FETCH_TODO_ADD_REQUEST_FAILED = 'FETCH_TODO_ADD_REQUEST_FAILED';

export const FETCH_TODO_DELETE_REQUEST = 'FETCH_TODO_DELETE_REQUEST';
export const FETCH_TODO_DELETE_REQUEST_SUCCESS = 'FETCH_TODO_DELETE_REQUEST_SUCCESS';
export const FETCH_TODO_DELETE_REQUEST_FAILED = 'FETCH_TODO_DELETE_REQUEST_FAILED';

export const FETCH_TODO_UPDATE_REQUEST = 'FETCH_TODO_UPDATE_REQUEST';
export const FETCH_TODO_UPDATE_REQUEST_SUCCESS = 'FETCH_TODO_UPDATE_REQUEST_SUCCESS';
export const FETCH_TODO_UPDATE_REQUEST_FAILED = 'FETCH_TODO_UPDATE_REQUEST_FAILED';

